### ISSUE TITLE
Key error during NSJ fasta generation

### ISSUE THREAD

**Issue by apuhegde** [ekawaler/pyQUILTS#4]
Hello,

I get the following error during the splice junctions step:

Traceback (most recent call last):
  File "/scratch/ahegde/pyQuilts/scripts/quilts_AH01.2.py", line 1965, in <module>
    translate(results_folder+"/log/", "alternative_frameshift.bed.dna")
  File "/scratch/ahegde/pyQuilts/scripts/quilts_AH01.2.py", line 857, in translate
    translated = translate_seq(sequence.upper(), strand)
  File "/scratch/ahegde/pyQuilts/scripts/quilts_AH01.2.py", line 813, in translate_seq
    translated += codon_map[sequence[i:i+3]]
KeyError: 'EGN'

I searched for "EGN" in the alternative_frameshift.bed.dna file but didn't find it. Not able to figure out a straightforward way of debugging this. Help is much appreciated!

**Comment by ekawaler** [comment]
Resolved
