### ISSUE TITLE
Key error when working with single VCF input (germline)

### ISSUE THREAD

**Issue by apuhegde** [ekawaler/pyQUILTS#6]
Hi,
I'm working with some sequencing data that only has germline VCFs, no somatic VCFs.
When I try to run quilts_v3.1.py script on it, it gives me the following error:

  warnings.warn("Failed to parse %s" % line)
Traceback (most recent call last):
  File "/scratch/ahegde/pyQuilts/test_SCCO/quilts_AH01.2.py", line 1871, in <module>
    sort_variants(results_folder+"/log/proteome.bed.dna", results_folder+"/log/proteome.bed.var", "proteome")
  File "/scratch/ahegde/pyQuilts/test_SCCO/quilts_AH01.2.py", line 730, in sort_variants
    changed_vars, aa_substs, indels = process_gene(header_line, second_header, exon_headers, exon_seqs, variants_map.get(name, []))
  File "/scratch/ahegde/pyQuilts/test_SCCO/quilts_AH01.2.py", line 510, in process_gene
    AA_old = codon_map[triplet_orig]
KeyError: 'A'

Could you please help me figure out what's causing this?
Please let me know if you need to examine some of the data files.

**Comment by ekawaler** [comment]
Resolved
